export const ANIMATION_REGISTRY: Record<string, { label: string; emoji: string }> = {
  elephant:     { label: "פיל הולך",               emoji: "🐘" },
  dog:          { label: "כלב הולך",               emoji: "🐶" },
  turkey:       { label: "הודו הולך בגאווה",        emoji: "🦃" },
  bird:         { label: "ציפור עפה",               emoji: "🐦" },
  totoro:       { label: "טוטורו הולך",             emoji: "🌿" },
  robot:        { label: "עין רובוט",              emoji: "🤖" },
  giraffe:      { label: "ג'ירפה מתמתחת",           emoji: "🦒" },
  runner:       { label: "דמות רצה",               emoji: "🏃" },
  frankenstein: { label: "פרנקנשטיין הולך",         emoji: "🧟" },
  death_dance:  { label: "ריקוד מוות",             emoji: "💀" },
  dancing_bug:  { label: "חרק רוקד",               emoji: "🐛" },
  cat:          { label: "חתול משחק",              emoji: "🐱" },
  crying:       { label: "אמוג'י בוכה",            emoji: "😭" },
  snowman:      { label: "איש שלג קופץ",           emoji: "⛄" },
  bear:         { label: "דוב רוקד",               emoji: "🐻" },
  piggy:        { label: "קופת חיסכון רוקדת",       emoji: "🐷" },
  survey:       { label: "דמות עם שאלון",           emoji: "📋" },
  frog:         { label: "צפרדע צדה חרק",           emoji: "🐸" },
  watermelon:   { label: "מר אבטיח",               emoji: "🍉" },
  strawberry:   { label: "תות לומד",               emoji: "🍓" },
  pencil:       { label: "עיפרון מצייר",            emoji: "✏️" },
  loading_hand: { label: "יד ממתינה",              emoji: "👋" },
  chicken:      { label: "תרנגולת הולכת",           emoji: "🐔" },
  jumping:      { label: "דמות קופצת",             emoji: "🤸" },
  camel:        { label: "גמל תינוק הולך",          emoji: "🐪" },
  toucan:       { label: "טוקן הולך",              emoji: "🦜" },
}

export const ANIMATION_DELAYS = [
  { value: 0,   label: "מיד" },
  { value: 5,   label: "5 שניות" },
  { value: 10,  label: "10 שניות" },
  { value: 30,  label: "30 שניות" },
  { value: 60,  label: "דקה" },
  { value: 120, label: "2 דקות" },
  { value: 180, label: "3 דקות" },
]

export const ANIMATION_POSITIONS = [
  { value: "across",       label: "חוצה את המסך" },
  { value: "center",       label: "מרכז" },
  { value: "corner-right", label: "פינה ימין" },
  { value: "corner-left",  label: "פינה שמאל" },
  { value: "top",          label: "למעלה" },
]
